repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.11.6
  hooks:
  - id: ruff
    args: [--fix]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy